version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: project_files/Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./project_files:/app
    command: python app.py

  db:
    image: nouchka/sqlite3:latest
    container_name: sqlite_db
    volumes:
      - sqlite_data:/var/lib/sqlite

volumes:
  sqlite_data:
    driver: local
